fixed binding issue #30
slimjs/slim.js pull request #54
Opened 2018-07-12 16:22 UTC by IceDune

bind attribute works with property names.

2018-07-12 16:25 UTC, IceDune commented
tried to fix it.. i guess now the bind property searches for attributes with any number of characters.

2018-07-16 12:26 UTC, eavichay commented
I think you should avoid regexp as it is costly. Since this is a simple check, you want to check attribute name index-of 'bind:' equals 0

WDYT?

2018-07-16 12:41 UTC, IceDune commented
@eavichay ,so you want it to work with attribute names with more than 0 characters right?

2018-07-16 12:54 UTC, eavichay commented
Just check that the attribute *starts with* `bind:` instead of regular expression which will have better performance. For hundreds of nodes on the DOM, every one is looked up and simple string functions are faster than regexp, where it can be avoided.

2018-07-16 15:53 UTC, IceDune commented
@eavichay , i've removed the regex for bind just as you suggested. Is it good or shall i improve it in any other way?

2018-07-16 20:29 UTC, eavichay requested changes

2018-07-16 20:29 UTC, eavichay commented on Slim.js
>      var tAttr = match[2];
`match` argument would be `bind:<something>` and therefore match[2] would be 'a'.

Did you run npm test before submitting?

2018-07-18 19:42 UTC, closed without merging